### PR TITLE
Fix 'Expected type after 'as''

### PR DESCRIPTION
**Pull request by Szymek887**

### CODE REVIEW

**Comment by Szymek887** [comment]
When there was a space between 'as' and '?' app won't build giving error 'Expected type after 'as''. After removing this space it started building

**Comment by Benimautner** [comment]
Can't verify IOS build as I have no IOS device to test it out, but docs say you're right.
Does it work when you build it?

**Comment by Szymek887** [comment]
Yes, when I build it, it works on iOS Simulator

**Comment by Benimautner** [comment]
Amazing, thanks!

**Pull request merged**
